Mac Mini Media Center - Installation & Einrichtung
==================================================
:author: Daniel Rodenburg
:toc:
:icons:
:numbered:

== Vorwort

Diese Anleitung beschreibt, wie ich einen älteren Mac Mini in einen
Media Center PC für meine Eltern umgewandelt habe.
Ziel waren niedriger Wartungsaufwand und leichte Bedienbarkeit.

== Systeminstallation

- Gleich am Anfang des Installers alles neu formatieren und partitionieren
- Deutsch als Hauptsprache installieren
- Keine Druckertreiber installieren
- Kein Rosetta, Kein Quicktime 7
- Keine persönlichen Daten eingeben (stattdessen einfach Fortfahren)
- Ein Administratorkonto anlegen, "administrator" o.Ä.

== Grundlegende Einrichtung
=== Benutzerkonzept

- Es gibt zwei Benutzer:
1. Den Administartor
2. Den kindergesicherten Benutzer

- Das Administratorkonto soll nur einmalig genutzt werden, danach werden nur noch die Login-Daten bei Änderungen von Systemeinstellungen benötigt, in das Konto selbst sollte sich nicht mehr eingeloggt werden.
- Das kindergesicherte Konto wird das des eigentlichen Media Center Benutzers. Nur Programme wie DVD Player, iTunes o.Ä. dürfen laufen. Das garantiert maximale Sicherheit, auch bei altem Update-Stand.

=== Als Administrator

- Updates einspielen (vom USB-Stick oder Internet)
- Kindergesichertes Benutzerkonto anlegen
- Apple Remote Pairen
- Evtl. Icons der Festplatten ändern
- Auflösung gleich passend einstellen

=== Als kindergesicherter User

- Benötigte Apple-Programme dauerhaft erlauben
  - Hierzu jede Situation 1mal durchspielen
- Benutzerbild ändern
- Finder einrichten
- In den Systemeinstellungen alle Sprachen außer Deutsch entfernen (nur dann spielt Front Row alles auf Deutsch ab)
- In iTunes und DVD Player die Spracheinstellungen machen


== Software-Installation
=== Obligatorische Software
- VLC +
  http://www.videolan.org/vlc
- TeamViewer +
  http://www.teamviewer.com/download/index.aspx
- NerdTool +
  http://balthamos.darkraver.net/applications.php?app=nerdtool
- Front Row Trailers +
  http://www.macupdate.com/app/mac/24116/front-row-trailers/
  - Perian
  - Flip4Mac
