Mac Mini Media Center - Installation & Einrichtung
==================================================
:author: Daniel Rodenburg
:toc:
:icons:
:numbered:
 
== Vorwort
 
Diese Anleitung beschreibt, wie ich gedenke einen älteren Mac Mini in einen
Media Center PC für meine Eltern umzuwandeln.
Ziel sind also niedriger Wartungsaufwand und leichte Bedienbarkeit.
 
== Systeminstallation

* Gleich am Anfang des Installers alles neu formatieren und partitionieren
* Deutsch als Hauptsprache installieren
* Keine Druckertreiber installieren
* Kein Rosetta, Kein Quicktime 7
// * X11 installieren (bringt ein paar nette Scripte mit)
// * XCode & Developer Tools installieren (oder später herunterladen) + http://developer.apple.com/technologies/xcode.html
* Keine persönlichen Daten eingeben (stattdessen mit dem roten X beenden)
* Ein Administratorkonto anlegen, "administrator" o.Ä.
 
== Grundlegende Einrichtung
=== Benutzerkonzept

* Es gibt drei Benutzer:
- Der Administartor
- Der normale Benutzer
- Den kindergesicherten Benutzer

* Das Administratorkonto soll nur einmalig genutzt werden, danach werden nur noch die Login-Daten bei Änderungen von Systemeinstellungen benötigt, in das Konto selbst sollte sich nicht mehr eingeloggt werden.
* Das normale Benutzerkonto wird nur selten verwendent - falls generelle Einstellungen vorgenommen werden sollen, oder um mit den Logindaten bestimmte Scripte zu starten.
* Das kindergesicherte Konto wird das des eigentlichen Media Center Benutzers. Nur Programme wie DVD Player, iTunes o.Ä. dürfen laufen. Das garantiert maximale Sicherheit, auch bei altem Update-Stand.

=== Als Administrator
 
* Updates einspielen (vom USB-Stick oder Internet)
* Normales Benutzerkonto anlegen
* Kindergesichertes Benutzerkonto anlegen
* Apple Remote Pairen
* Evtl. Icons der Festplatten ändern
 
=== Als normaler User
 
* Hostname ändern
* Systemeinstellungen je nach Wunsch ändern

=== Admin-User im Login-Fenster ausblenden
----
## Benutzer im Login-Fenster verstecken
# Generell:
# sudo defaults write /Library/Preferences/com.apple.loginwindow HiddenUsersList -array-add user1 user2 user3 user4
# user1, etc. muss der Kurzname des Benutzers sein.
# Den kann man mit Rechtsklick auf den Benutzer in den Systemeinstellungen herausfinden
# Für administrator
$ su administrator
$ sudo defaults write /Library/Preferences/com.apple.loginwindow HiddenUsersList -array-add administrator normaluser
# Zum wieder anzeigen:
# sudo defaults delete /Library/Preferences/com.apple.loginwindow HiddenUsersList
----

=== Als kindergesicherter User

* Benötigte Apple-Programme dauerhaft erlauben
* Benutzerbild ändern
* Finder einrichten
 
== User-Interface aufhübschen 
=== Versteckte OS X Einstellungen machen
----
## Dock
# Das Dock in den 2D Modus schalten
$ defaults write com.apple.dock no-glass -boolean YES
  
# Externe Festplatten schon vor User-Login mounten
# sudo defaults write /Library/Preferences/SystemConfiguration/autodiskmount AutomountDisksWithoutUserLogin -bool true
  
# Keine iTunes Store Arrows mehr
$ defaults write com.apple.iTunes show-store-arrow-links -bool FALSE
$ ﻿defaults write com.apple.iTunes show-store-link-arrows 0
 
# Kein Ping DropDown mehr
$ defaults write com.apple.iTunes hide-ping-dropdown 1
 
# Kein Ping (und kein iTunes Store) mehr
# defaults write com.apple.iTunes disablePingSidebar 1﻿ 
 
## QuickTime X 
# Autoplay
$ defaults write com.apple.QuickTimePlayerX MGPlayMovieOnOpen 1 
 
# Werte setzen
$ killall Dock
$ killall Finder
----
 
== Software-Installation
=== Obligatorische Software
* Air Video Server +
  http://www.inmethod.com/air-video/index.html
* VLC +
  http://www.videolan.org/vlc
* TeamViewer +
  http://www.teamviewer.com/download/index.aspx
* Google Chrome +
  http://www.google.com/chrome
* JDownloader +
  http://jdownloader.org/download/index
* NerdTool +
  http://balthamos.darkraver.net/applications.php?app=nerdtool
* The Unarchiver +
  http://wakaba.c3.cx/s/apps/unarchiver.html
* UnRarX +
  http://www.unrarx.com
* CoverSutra +
  http://www.sophiestication.com/coversutra
 

